-- ZOS constants used by Verdant, captured by value at module load time.
-- Per SPEC_01 §4.3 / §6, this is the by-value form: M.X = X. Consumers
-- read through Verdant.zenimax.constants and may local-cache for hot
-- paths (SPEC_01 §5.2).

Verdant = Verdant or {}
Verdant.zenimax = Verdant.zenimax or {}
local Verdant = Verdant

Verdant.zenimax.constants = {}
local M = Verdant.zenimax.constants

-- ── event ids ─────────────────────────────────────────────────────────────
M.EVENT_ADD_ON_LOADED              = EVENT_ADD_ON_LOADED
M.EVENT_COMBAT_EVENT               = EVENT_COMBAT_EVENT
M.EVENT_EFFECT_CHANGED             = EVENT_EFFECT_CHANGED
M.EVENT_GROUP_MEMBER_JOINED        = EVENT_GROUP_MEMBER_JOINED
M.EVENT_GROUP_MEMBER_LEFT          = EVENT_GROUP_MEMBER_LEFT
M.EVENT_GROUP_UPDATE               = EVENT_GROUP_UPDATE
M.EVENT_PLAYER_ACTIVATED           = EVENT_PLAYER_ACTIVATED
M.EVENT_PLAYER_DEACTIVATED         = EVENT_PLAYER_DEACTIVATED
M.EVENT_PLAYER_COMBAT_STATE        = EVENT_PLAYER_COMBAT_STATE
M.EVENT_ACTION_SLOT_ABILITY_USED   = EVENT_ACTION_SLOT_ABILITY_USED

-- ── EVENT_MANAGER:AddFilterForEvent filter keys ───────────────────────────
M.REGISTER_FILTER_SOURCE_COMBAT_UNIT_TYPE = REGISTER_FILTER_SOURCE_COMBAT_UNIT_TYPE
M.REGISTER_FILTER_TARGET_COMBAT_UNIT_TYPE = REGISTER_FILTER_TARGET_COMBAT_UNIT_TYPE
M.REGISTER_FILTER_COMBAT_RESULT           = REGISTER_FILTER_COMBAT_RESULT
M.REGISTER_FILTER_IS_ERROR                = REGISTER_FILTER_IS_ERROR
M.REGISTER_FILTER_UNIT_TAG                = REGISTER_FILTER_UNIT_TAG

-- ── combat unit type ──────────────────────────────────────────────────────
M.COMBAT_UNIT_TYPE_PLAYER     = COMBAT_UNIT_TYPE_PLAYER
M.COMBAT_UNIT_TYPE_PLAYER_PET = COMBAT_UNIT_TYPE_PLAYER_PET
M.COMBAT_UNIT_TYPE_GROUP      = COMBAT_UNIT_TYPE_GROUP

-- ── action results (heals) ────────────────────────────────────────────────
M.ACTION_RESULT_HEAL                = ACTION_RESULT_HEAL
M.ACTION_RESULT_HOT_TICK            = ACTION_RESULT_HOT_TICK
M.ACTION_RESULT_CRITICAL_HEAL       = ACTION_RESULT_CRITICAL_HEAL
M.ACTION_RESULT_HOT_TICK_CRITICAL   = ACTION_RESULT_HOT_TICK_CRITICAL
M.ACTION_RESULT_HEAL_ABSORBED       = ACTION_RESULT_HEAL_ABSORBED

-- ── action results (damage / shield) ──────────────────────────────────────
M.ACTION_RESULT_DAMAGE              = ACTION_RESULT_DAMAGE
M.ACTION_RESULT_DOT_TICK            = ACTION_RESULT_DOT_TICK
M.ACTION_RESULT_CRITICAL_DAMAGE     = ACTION_RESULT_CRITICAL_DAMAGE
M.ACTION_RESULT_DOT_TICK_CRITICAL   = ACTION_RESULT_DOT_TICK_CRITICAL
M.ACTION_RESULT_BLOCKED_DAMAGE      = ACTION_RESULT_BLOCKED_DAMAGE
M.ACTION_RESULT_FALL_DAMAGE         = ACTION_RESULT_FALL_DAMAGE
M.ACTION_RESULT_DAMAGE_SHIELDED     = ACTION_RESULT_DAMAGE_SHIELDED

-- ── effect results ────────────────────────────────────────────────────────
M.EFFECT_RESULT_GAINED        = EFFECT_RESULT_GAINED
M.EFFECT_RESULT_FADED         = EFFECT_RESULT_FADED
M.EFFECT_RESULT_UPDATED       = EFFECT_RESULT_UPDATED
M.EFFECT_RESULT_FULL_REFRESH  = EFFECT_RESULT_FULL_REFRESH
M.EFFECT_RESULT_TRANSFER      = EFFECT_RESULT_TRANSFER
